# Generated by Django 3.2.16 on 2023-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField(auto_now_add=True)),
                ('age', models.CharField(max_length=250)),
                ('gender', models.CharField(default=False, max_length=250)),
                ('phnum', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=200)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=250)),
                ('courses', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('mp', models.CharField(max_length=250)),
            ],
        ),
    ]
